### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by activestylus** [everythingwillbetakenaway/DX7-Supercollider#3]
Very cool project!

Really wanting to play around but could not figure out what app I'm supposed to open this in. The extensions are associated with image editing and tax software, lol. How are you running this bad boy?

**Comment by everythingwillbetakenaway** [comment]
-You don't need to open DX7.afx file. It just needs to be in the same directory as DX7.scd. 
-Just open DX7.scd in Supercollider and run the big chunk of code starting from line 35 and it's ready to use. Then run the mainCaller functions for new notes and to close notes send zero velocity from mainCaller functions.
-The only requirement is to install SC3-Plugins Ugen library because I use FM7.ar Ugen at the heart of all operation.

**Comment by activestylus** [comment]
Thanks for the helpful info
